### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by rube-de** [DefiLlama/defillama-extension#23]
Please release the extension also for firefox.

**Comment by 0xFrostytie** [comment]
Second this

**Comment by nicolas-g** [comment]
⬆️

**Comment by g1nt0ki** [comment]
@nicolas-g @0xFrostytie @nicolas-g  We now have firefox support: you can install it from here: https://github.com/DefiLlama/defillama-extension/releases/tag/v0.0.8


Or, you can build from source with "npm run build_firefox" let me know if you have any questions or doubts

**Comment by 0xFrostytie** [comment]
> @nicolas-g @0xFrostytie @nicolas-g We now have firefox support: you can install it from here: https://github.com/DefiLlama/defillama-extension/releases/tag/v0.0.8
> 
> Or, you can build from source with "npm run build_firefox" let me know if you have any questions or doubts

You guys are goated for this. I wanted to build it myself but I wasn't really skilled as that. Very thankful!
