### ISSUE TITLE
Misleading README

### ISSUE THREAD

**Issue by trocher** [DefiLlama/defillama-extension#30]
In `README.md`, it is written that 

> we only request access to Etherscan and similar blockchain explorers, in order to inject llama token prices and wallet tags.

However, it seems that with the new version, to allow for a dynamic list of supported websites, the extension requests read and change site data permission on all site, this behaviour should probably be described and explained in the README as it is in the `Explanations for permissions requested` section of the chrome web store page

**Comment by 0xStrobe** [comment]
Thank you for raising this, we added a feature to filter scams and missed updating the readme.

ref: 
https://twitter.com/0xngmi/status/1752790386114785442
https://twitter.com/0xngmi/status/1771225502377807889
