### ISSUE TITLE
[Bug] False Positive on Quote Tweets

### ISSUE THREAD

**Issue by 0xOsprey** [DefiLlama/defillama-extension#39]
In this example: https://twitter.com/laurashin/status/1789690433041256877

Laura's Quote Tweet is marked as phishing

<img width="598" alt="image" src="https://github.com/DefiLlama/defillama-extension/assets/42589294/5fe5b8cb-0fd1-4938-86e2-7df9740d1629">

**Comment by ShaunLWM** [comment]
![image](https://github.com/DefiLlama/defillama-extension/assets/37434846/b8e25728-a9c6-4a15-a0cf-4c09e9bc23a8)
Looks good on my side though

**Comment by 0xOsprey** [comment]
Yup can't reproduce now - Closing
